
# This is a TOML document. Boom.

regionId = "cn-beijing"

[[firewall]]
id = "dds-instance-id"
name = "dds-description-name"
groupName = "shenzhen"
modifyMode = "Cover"
type = "Dds"

[[firewall]]
id = "r-instance-id"
name = "r-description-name"
groupName = "shenzhen"
modifyMode = "Cover"
type = "R-kvstore"
